version: '3.8'

services:
  db:
    image: postgres:16
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: back_app
    ports:
      - 1289:8000
    depends_on:
      - db
    command: ['/backend_app/docker/app.sh']

  bot:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: bot_app
    depends_on:
      - db
      - app
    command: ['/backend_app/docker/bot.sh']