"""Upgrade participant table

Revision ID: 0eb29067d8ce
Revises: 698530017f44
Create Date: 2024-09-22 19:19:12.943961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb29067d8ce'
down_revision: Union[str, None] = '698530017f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_time_activity_bot',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('time_activity_bot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['time_activity_bot_id'], ['time_activity_bot.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'time_activity_bot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_time_activity_bot')
    # ### end Alembic commands ###
