"""Upgrade table answer

Revision ID: 3280538a90c5
Revises: bdd91197cba2
Create Date: 2024-10-04 20:17:35.565900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3280538a90c5'
down_revision: Union[str, None] = 'bdd91197cba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_status')
    op.add_column('answer', sa.Column('a_cancel_registration', sa.String(), nullable=False))
    op.add_column('answer', sa.Column('a_if_user_say_no_now', sa.String(), nullable=False))
    op.add_column('answer', sa.Column('a_if_bot_dont_understand', sa.String(), nullable=False))
    op.add_column('answer', sa.Column('a_incorrect_phone_number', sa.String(), nullable=False))
    op.add_column('answer', sa.Column('a_no_found_raffle', sa.String(), nullable=False))
    op.add_column('answer', sa.Column('a_error_raffle', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'a_error_raffle')
    op.drop_column('answer', 'a_no_found_raffle')
    op.drop_column('answer', 'a_incorrect_phone_number')
    op.drop_column('answer', 'a_if_bot_dont_understand')
    op.drop_column('answer', 'a_if_user_say_no_now')
    op.drop_column('answer', 'a_cancel_registration')
    op.create_table('bot_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('time_change_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bot_status_pkey')
    )
    # ### end Alembic commands ###
