"""Add new tables QStepRegistration and ARegistration for tg_bot registration

Revision ID: 4816d2c2befd
Revises: e22136de7e70
Create Date: 2024-09-30 18:31:08.832611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4816d2c2befd'
down_revision: Union[str, None] = 'e22136de7e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_end_registration_message', sa.String(), nullable=False),
    sa.Column('a_phone_number_user', sa.String(), nullable=False),
    sa.Column('a_name_user', sa.String(), nullable=False),
    sa.Column('a_last_name_user', sa.String(), nullable=False),
    sa.Column('a_middle_name_user', sa.String(), nullable=False),
    sa.Column('a_random_key_user', sa.String(), nullable=False),
    sa.Column('a_participant_code', sa.String(), nullable=False),
    sa.Column('a_message_for_winners', sa.String(), nullable=False),
    sa.Column('a_message_for_all_users', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('q_first', sa.String(), nullable=False),
    sa.Column('q_second', sa.String(), nullable=False),
    sa.Column('q_second_raffle_condition_url', sa.String(), nullable=False),
    sa.Column('q_third', sa.String(), nullable=False),
    sa.Column('q_third_url_privacy', sa.String(), nullable=False),
    sa.Column('q_fourth_introduce', sa.String(), nullable=False),
    sa.Column('q_fourth_phone_number', sa.String(), nullable=False),
    sa.Column('q_fives_name', sa.String(), nullable=False),
    sa.Column('q_sixth_lastname', sa.String(), nullable=False),
    sa.Column('q_seventh_middle_name', sa.String(), nullable=False),
    sa.Column('q_eighth_sales_receipt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('answer')
    # ### end Alembic commands ###
