"""empty message

Revision ID: 698530017f44
Revises: e3d1cda2cbe6
Create Date: 2024-09-08 21:43:31.621777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698530017f44'
down_revision: Union[str, None] = 'e3d1cda2cbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_activity_bot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_activity_bot')
    # ### end Alembic commands ###
