"""Upgrade all table

Revision ID: 6cd96904bdae
Revises: 7a23904807f2
Create Date: 2024-09-24 23:23:18.297801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd96904bdae'
down_revision: Union[str, None] = '7a23904807f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_winner',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['winner.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'winner_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant_winner')
    # ### end Alembic commands ###
