"""Modify table Participant and TimeActivityBot(add field for connect new Winner table)

Revision ID: 923cb9e215ee
Revises: 0eb29067d8ce
Create Date: 2024-09-24 13:36:34.529852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923cb9e215ee'
down_revision: Union[str, None] = '0eb29067d8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['raffle_id'], ['time_activity_bot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('time_activity_bot', sa.Column('amount_winner', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_activity_bot', 'amount_winner')
    op.drop_table('winner')
    # ### end Alembic commands ###
