"""Delete some column in table ARegistration

Revision ID: bdd91197cba2
Revises: 4816d2c2befd
Create Date: 2024-09-30 18:37:09.729184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd91197cba2'
down_revision: Union[str, None] = '4816d2c2befd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'a_last_name_user')
    op.drop_column('answer', 'a_middle_name_user')
    op.drop_column('answer', 'a_name_user')
    op.drop_column('answer', 'a_random_key_user')
    op.drop_column('answer', 'a_participant_code')
    op.drop_column('answer', 'a_phone_number_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('a_phone_number_user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('a_participant_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('a_random_key_user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('a_name_user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('a_middle_name_user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('answer', sa.Column('a_last_name_user', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
