"""empty message

Revision ID: f3b234c78851
Revises: 1deb52ce4e06
Create Date: 2024-09-25 01:31:29.612266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b234c78851'
down_revision: Union[str, None] = '1deb52ce4e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner_time_activity_bot',
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('time_activity_bot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['time_activity_bot_id'], ['time_activity_bot.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['winner.id'], ),
    sa.PrimaryKeyConstraint('winner_id', 'time_activity_bot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winner_time_activity_bot')
    # ### end Alembic commands ###
